"""Record a deploy to s3://BUCKET/deployments/STAGE/ as a self-contained bundle.

Everything written here is non-secret (values come from samconfig.toml, git, and
config.yaml). Nothing outside the f5kb bucket is touched. After a deploy,
`aws s3 sync s3://<bucket>/deployments/<stage>/ ./f5kb-deploy` yields a folder
with the template, deploy params, pinned layer deps, a config snapshot, and a
step-by-step DEPLOY.md runbook — enough for a fresh operator to redeploy.

Keys written (prefix = deployments/{stage}/):

  DEPLOY.md               — human runbook (prereqs → build → deploy → sync-config)
  manifest.json           — bundle index: what each file is + git provenance
  config.json             — current deploy config snapshot (params + git SHA)
  ssm-required.json       — SSM parameter paths (names only, never values)
  deploy-log.jsonl        — append-only deploy history
  template.yaml           — the SAM/CloudFormation template that was deployed
  samconfig.toml          — deploy params for `sam deploy --config-env <stage>`
  layer-requirements.txt  — pinned Lambda-layer deps (from uv.lock)
  config-types.json       — snapshot of config.yaml's types: block (see sync-config)

`config.json`, `ssm-required.json`, `DEPLOY.md`, `manifest.json`, and the file
snapshots are OVERWRITTEN each run (current state); `deploy-log.jsonl` is appended.

Run after every successful `sam deploy`:

    uv run python scripts/record_deploy.py --stage staging --bucket f5kb-articles-<acct>-staging
    (deploy.sh does this automatically)
"""

from __future__ import annotations

import argparse
import datetime
import json
import subprocess
import sys
import tomllib
from pathlib import Path

# SSM parameter NAMES (not values) per stage — keep in sync with template.yaml.
_SSM_REQUIRED = [
    "/f5kb/{stage}/slack/webhook-url",
    "/f5kb/{stage}/slack/signing-secret",
]
_SSM_OPTIONAL = [
    "/f5kb/{stage}/github/token",
]

# File-backed bundle members: (bundle filename, repo path, S3 content type).
# Read from the repo root at record time; a missing file is warned + skipped.
_BUNDLE_FILES = [
    ("template.yaml", Path("template.yaml"), "text/yaml"),
    ("samconfig.toml", Path("samconfig.toml"), "application/toml"),
    ("layer-requirements.txt", Path("layer/requirements.txt"), "text/plain"),
]


def _git(cmd: list[str]) -> str:
    try:
        return subprocess.check_output(["git"] + cmd, text=True, stderr=subprocess.DEVNULL).strip()
    except subprocess.CalledProcessError:
        return ""


def _parse_param_overrides(raw: str) -> dict[str, str]:
    """Parse samconfig `parameter_overrides` string into a dict.

    Handles: 'Key=Value Key2="quoted value with spaces"'
    """
    import shlex

    result: dict[str, str] = {}
    for token in shlex.split(raw):
        if "=" in token:
            k, _, v = token.partition("=")
            result[k.strip()] = v.strip()
    return result


def _read_text(path: Path) -> str | None:
    """Read a repo file as UTF-8; return None (with a warning) if unavailable."""
    try:
        return path.read_text(encoding="utf-8")
    except OSError as exc:
        print(f"    [warn] skipping bundle file {path}: {exc}", file=sys.stderr)
        return None


def _snapshot_config_types() -> str | None:
    """Return config.yaml's types: block as JSON — the same content sync-config pushes."""
    try:
        from f5kb.config.loader import types_for_lambda

        return json.dumps(types_for_lambda("config.yaml"), indent=2) + "\n"
    except Exception as exc:  # noqa: BLE001 — snapshot is best-effort, never fatal
        print(f"    [warn] could not snapshot config types: {exc}", file=sys.stderr)
        return None


def _build_deploy_md(
    *,
    stage: str,
    stack_name: str,
    region: str,
    bucket: str,
    param_overrides: dict[str, str],
    ssm_required: list[str],
    ssm_optional: list[str],
    git_sha: str,
    git_sha_short: str,
    git_tag: str,
    now: str,
) -> str:
    """Author the human-facing deploy runbook for this stage."""
    ssm_create = "\n".join(
        f"aws ssm put-parameter --name '{p}' --type SecureString --value '...' --region {region}" for p in ssm_required
    )
    ssm_opt_lines = "\n".join(f"- `{p}` (optional)" for p in ssm_optional) or "- (none)"
    overrides_lines = "\n".join(f"- `{k}` = `{v}`" for k, v in param_overrides.items()) or "- (none)"
    build_ref = git_tag or git_sha_short or "(unknown — commit the repo before deploying)"

    return f"""# f5kb deploy runbook — `{stage}`

> Generated by `scripts/record_deploy.py` on **{now}** from git
> `{git_sha or "(no sha)"}`{f" (tag `{git_tag}`)" if git_tag else ""}.
> Non-secret. This folder is a snapshot; the source of truth is the git repo.

This bundle lives at `s3://{bucket}/deployments/{stage}/`. To grab it:

```bash
aws s3 sync s3://{bucket}/deployments/{stage}/ ./f5kb-deploy
```

## What deployed here

| | |
|---|---|
| Stage | `{stage}` |
| Stack name | `{stack_name}` |
| Region | `{region}` |
| Artifact bucket | `{bucket}` |
| Git ref | `{build_ref}` |

CloudFormation parameter overrides for this stage:

{overrides_lines}

## Bundle contents

- `DEPLOY.md` — this runbook
- `manifest.json` — machine-readable index of the bundle
- `config.json` — deploy config snapshot (params + git provenance)
- `ssm-required.json` — SSM parameter names (never values)
- `deploy-log.jsonl` — append-only deploy history
- `template.yaml` — the SAM/CloudFormation template
- `samconfig.toml` — deploy params for `sam deploy --config-env {stage}`
- `layer-requirements.txt` — pinned Lambda-layer deps
- `config-types.json` — snapshot of `config.yaml`'s `types:` block

> The Lambda **code zips are not in this bundle** — they are ~25 MB each and are
> already stored, keyed by content hash, in the SAM managed bucket. Rebuild them
> from the git ref below with `sam build`; the result is byte-reproducible.

## Prerequisites

- `aws` CLI authenticated to account for `{bucket}` (region `{region}`)
- `sam` CLI installed
- `uv` installed
- The git repo checked out at the ref above:
  ```bash
  git checkout {build_ref}
  ```

## 1. Create SSM SecureStrings (BEFORE deploying)

Secrets are never stored in S3 or the repo — they live in SSM. Create them once
per stage:

```bash
{ssm_create}
```

Optional parameters:

{ssm_opt_lines}

## 2. Build

```bash
sam build
```

## 3. Deploy

```bash
sam deploy --config-env {stage}
```

(or `bash scripts/deploy.sh {stage}` from the repo, which validates SSM params,
builds, deploys, and re-records this bundle.)

## 4. Sync the pipeline config — REQUIRED

The Dump Lambda reads `config.yaml`'s `types:` block from S3, not from the zip.
**Skipping this makes multi-word types return zero articles.**

```bash
make sync-config BUCKET={bucket}
# or: uv run python scripts/sync_lambda_config.py --bucket {bucket}
```

`config-types.json` in this bundle is the snapshot that was live at record time —
compare it against `s3://{bucket}/lambda/config/types.json` if results look wrong.

## 5. Verify

```bash
aws cloudformation describe-stacks --stack-name {stack_name} --region {region} \\
  --query 'Stacks[0].StackStatus' --output text
```

Expect `CREATE_COMPLETE` or `UPDATE_COMPLETE`.
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--stage", required=True, choices=["staging", "prod"])
    parser.add_argument("--bucket", required=True, help="S3 bucket name")
    parser.add_argument("--region", default="us-east-2")
    parser.add_argument("--dry-run", action="store_true", help="print JSON, do not upload")
    args = parser.parse_args()

    stage = args.stage
    bucket = args.bucket
    now = datetime.datetime.now(datetime.timezone.utc).isoformat().replace("+00:00", "Z")

    # ── Read samconfig.toml ─────────────────────────────────────────────────
    samconfig_path = Path("samconfig.toml")
    if not samconfig_path.exists():
        print("ERROR: samconfig.toml not found — run from the repo root", file=sys.stderr)
        return 1

    with open(samconfig_path, "rb") as f:
        samconfig = tomllib.load(f)

    deploy_params = samconfig.get(stage, {}).get("deploy", {}).get("parameters", {})
    stack_name = deploy_params.get("stack_name", f"f5kb-{stage}")
    region = deploy_params.get("region", args.region)
    raw_overrides = deploy_params.get("parameter_overrides", "")
    param_overrides = _parse_param_overrides(raw_overrides) if raw_overrides else {}

    # ── Gather git context ──────────────────────────────────────────────────
    git_sha = _git(["rev-parse", "HEAD"])
    git_sha_short = git_sha[:8] if git_sha else ""
    git_branch = _git(["rev-parse", "--abbrev-ref", "HEAD"])
    git_tag = _git(["describe", "--tags", "--exact-match"]) or ""
    git_dirty = bool(_git(["status", "--porcelain"]))
    deployed_by = _git(["config", "user.email"]) or ""

    # ── Build SSM param lists (names only, no values) ───────────────────────
    ssm_required = [p.format(stage=stage) for p in _SSM_REQUIRED]
    ssm_optional = [p.format(stage=stage) for p in _SSM_OPTIONAL]

    # ── config.json (current deploy state) ──────────────────────────────────
    config = {
        "schema": "f5kb.deploy.v1",
        "stage": stage,
        "stack_name": stack_name,
        "region": region,
        "bucket": bucket,
        "parameter_overrides": param_overrides,
        "ssm_required": ssm_required,
        "ssm_optional": ssm_optional,
        "last_deploy": {
            "deployed_at": now,
            "deployed_by": deployed_by,
            "git_sha": git_sha,
            "git_sha_short": git_sha_short,
            "git_branch": git_branch,
            "git_tag": git_tag,
            "git_dirty": git_dirty,
        },
    }

    # ── ssm-required.json (stable reference for new deployers) ──────────────
    ssm_doc = {
        "schema": "f5kb.deploy.v1",
        "stage": stage,
        "note": ("SSM SecureStrings — create these BEFORE deploying. Never put raw values in S3 or the repo."),
        "create_commands": [
            f"aws ssm put-parameter --name '{p}' --type SecureString --value '...' --region {region}"
            for p in ssm_required
        ],
        "required": ssm_required,
        "optional": ssm_optional,
    }

    # ── deploy-log.jsonl entry (append-only history) ─────────────────────────
    log_entry = {
        "deployed_at": now,
        "stage": stage,
        "stack_name": stack_name,
        "deployed_by": deployed_by,
        "git_sha": git_sha,
        "git_sha_short": git_sha_short,
        "git_branch": git_branch,
        "git_tag": git_tag,
        "git_dirty": git_dirty,
    }

    # ── Deploy bundle: self-contained + instructions ─────────────────────────
    # Generated members (authored here) + file-backed members (read from repo).
    deploy_md = _build_deploy_md(
        stage=stage,
        stack_name=stack_name,
        region=region,
        bucket=bucket,
        param_overrides=param_overrides,
        ssm_required=ssm_required,
        ssm_optional=ssm_optional,
        git_sha=git_sha,
        git_sha_short=git_sha_short,
        git_tag=git_tag,
        now=now,
    )
    config_types = _snapshot_config_types()

    # Collect file-backed members that actually exist on disk.
    file_members: list[tuple[str, str, str]] = []  # (filename, text, content_type)
    for filename, path, content_type in _BUNDLE_FILES:
        text = _read_text(path)
        if text is not None:
            file_members.append((filename, text, content_type))

    # manifest.json — one-line description of every bundle file, + git provenance.
    _DESCRIPTIONS = {
        "DEPLOY.md": "Human runbook: prereqs, build, deploy, sync-config, verify.",
        "manifest.json": "This index of bundle contents and git provenance.",
        "config.json": "Deploy config snapshot (parameters + git SHA).",
        "ssm-required.json": "SSM parameter names to pre-create (never values).",
        "deploy-log.jsonl": "Append-only history of deploys to this stage.",
        "template.yaml": "The SAM/CloudFormation template that was deployed.",
        "samconfig.toml": "Deploy params for `sam deploy --config-env <stage>`.",
        "layer-requirements.txt": "Pinned Lambda-layer dependencies (from uv.lock).",
        "config-types.json": "Snapshot of config.yaml's types: block (see sync-config).",
    }
    present = {"DEPLOY.md", "manifest.json", "config.json", "ssm-required.json", "deploy-log.jsonl"}
    present |= {name for name, _, _ in file_members}
    if config_types is not None:
        present.add("config-types.json")
    manifest = {
        "schema": "f5kb.deploy-bundle.v1",
        "stage": stage,
        "generated_at": now,
        "bucket": bucket,
        "prefix": f"deployments/{stage}",
        "git_sha": git_sha,
        "git_sha_short": git_sha_short,
        "git_tag": git_tag,
        "git_dirty": git_dirty,
        "files": {name: _DESCRIPTIONS[name] for name in sorted(present)},
    }

    if args.dry_run:
        print("=== deployments/{stage}/DEPLOY.md ===".format(stage=stage))
        print(deploy_md)
        print("=== deployments/{stage}/manifest.json ===".format(stage=stage))
        print(json.dumps(manifest, indent=2))
        print("\n=== deployments/{stage}/config.json ===".format(stage=stage))
        print(json.dumps(config, indent=2))
        print("\n=== deployments/{stage}/ssm-required.json ===".format(stage=stage))
        print(json.dumps(ssm_doc, indent=2))
        print("\n=== deployments/{stage}/deploy-log.jsonl (append) ===".format(stage=stage))
        print(json.dumps(log_entry))
        print("\n=== file-backed bundle members (would upload) ===")
        for name, _, ctype in file_members:
            print(f"  {name}  ({ctype})")
        if config_types is not None:
            print("  config-types.json  (application/json)")
        return 0

    import boto3

    s3 = boto3.client("s3", region_name=args.region)
    prefix = f"deployments/{stage}"

    def _put(key_suffix: str, body: str, content_type: str) -> None:
        s3.put_object(
            Bucket=bucket,
            Key=f"{prefix}/{key_suffix}",
            Body=body.encode("utf-8"),
            ContentType=content_type,
        )
        print(f"    uploaded s3://{bucket}/{prefix}/{key_suffix}", file=sys.stderr)

    # config.json — overwrite (current state)
    _put("config.json", json.dumps(config, indent=2) + "\n", "application/json")

    # ssm-required.json — overwrite (stable reference)
    _put("ssm-required.json", json.dumps(ssm_doc, indent=2) + "\n", "application/json")

    # DEPLOY.md + manifest.json — overwrite (current runbook + index)
    _put("DEPLOY.md", deploy_md, "text/markdown")
    _put("manifest.json", json.dumps(manifest, indent=2) + "\n", "application/json")

    # File-backed members — overwrite (snapshot of what was deployed)
    for name, text, content_type in file_members:
        _put(name, text, content_type)

    # config-types.json — overwrite (best-effort snapshot)
    if config_types is not None:
        _put("config-types.json", config_types, "application/json")

    # deploy-log.jsonl — append (download existing, append, re-upload)
    log_key = f"{prefix}/deploy-log.jsonl"
    try:
        existing = s3.get_object(Bucket=bucket, Key=log_key)["Body"].read().decode("utf-8")
        if existing and not existing.endswith("\n"):
            existing += "\n"
    except s3.exceptions.NoSuchKey:
        existing = ""
    except Exception:
        existing = ""

    appended = existing + json.dumps(log_entry) + "\n"
    s3.put_object(
        Bucket=bucket,
        Key=log_key,
        Body=appended.encode("utf-8"),
        ContentType="application/x-ndjson",
    )
    print(f"    appended  s3://{bucket}/{log_key}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
